#服务器配置
server:
  port: 8081
  connection-timeout: 60000
  servlet:
    context-path: "/manager"
  tomcat:
    basedir: "manager-tomcat"
    uri-encoding: "utf-8"
    max-connections: 65535
    max-threads: 1000

#日志级别
logging:
  level:
    root: "info"
    com.manager.manager.mapper: DEBUG

mybatis:
  config-location: "classpath:mybatis/mybatis-config.xml"

#application:
#  db:
#    dbroute:
#      # tx - transactional非propagation.required方法用从库; name - 方法名称前缀带select, query, get用从库
#      dbroutetype: "tx"
#    master:
#      driverClassName: "com.mysql.jdbc.Driver"
#      url: "jdbc:mysql://127.0.0.1:3306/manager?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true"
#      username: "root"
#      password: "19951110lsy."
#      maximum-pool-size: 500
#      minimum-idle: 5
#    slave:
#      driverClassName: "com.mysql.jdbc.Driver"
#      url: "jdbc:mysql://127.0.0.1:3306/manager?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true"
#      username: "root"
#      password: "19951110lsy."
#      maximum-pool-size: 500
#      minimum-idle: 5

spring:
  application:
    name: "manager"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19951110lsy.
    driver-class-name: com.mysql.jdbc.Driver

#健康检查
management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  server:
    port: 18080
    servlet:
      context-path: "/"
    ssl:
      enabled: false
  #优雅下线 服务端配置 http://localhost:18080/admin/shutdown
  endpoint:
    health:
      show-details: "always"
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
  #禁用不需要健康检查的组件
  health:
    redis:
      enabled: false
    mail:
      enabled: false
    nacos-config:
      enabled: false

